env:
  global:
    - CC_TEST_REPORTER_ID=1f3dee90870bee4a1946b3b12521369414a9e06e84f982728fc729990ebebc2f
language: ruby
rvm:
  # Build on the latest stable of all supported Rubies (https://www.ruby-lang.org/en/downloads/):
  - 2.5.8
  - 2.6.6
  - 2.7.1
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rubocop
  - bundle exec rspec spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  # https://docs.travis-ci.com/user/uploading-artifacts/
  artifacts:
    paths:
      - Gemfile.lock
